---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: centos-6.4

suites:
  - name: default
    run_list: sandy-dev::default
    attributes:
      chruby:
        default: 'embedded'
      postgresql:
        password:
          postgres: 's4nd1-d3v-D4taBa5e'
