---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: chef/centos-6.6

suites:
  - name: default
    run_list:
      - recipe[sandy-avhrr::default]
    attributes:
      polar2grid:
        url: http://mirrors.gina.alaska.edu/SSEC/CSPP/CSPP_IMAPP_POLAR2GRID_V1.2.tar.gz
