---
driver:
  name: vagrant
  vm_hostname: sandy-ldm.local
  
provisioner:
  name: chef_zero

platforms:
  - name: chef/centos-6.6

suites:
  - name: default
    run_list:
      - recipe[sandy-ldm::default]
    attributes:
      sandy-ldm:
        data_bag: sandy-ldm-test
